### ISSUE TITLE
having issues querying versions

### ISSUE THREAD

**Issue by tbeason** [johnnychen94/jill.py#35]
Things like `jill install` and `jill install 1.5` were hanging for a long long time at the querying versions step. 

`jill install 1.5.0` worked without issue.

**Comment by johnnychen94** [comment]
Thanks for trying this!

Yes, I'm aware of that. It happens when a new version comes out and [`jill` doesn't know about it yet](https://github.com/johnnychen94/jill.py/blob/master/jill/config/releases.csv). If you specify `x.y.z` then jill assumes that version exists and directly tries to download it. If you try `jill install 1.0` it would just be as fast as `jill install 1.0.5`.

There're two options to optimize this process:

* read version info from official s3 bucket: #18 
* use async query, currently it's a [plain for loop](https://github.com/johnnychen94/jill.py/blob/8c117fd1d3ace5e9da779ea6117e4a82c6c970b1/jill/utils/source_utils.py#L192-L207): I'm not very familiar with this so it needs time

Another way to boost this is to limit querying servers, e.g., `jill install --upstream Official`.

**Comment by johnnychen94** [comment]
please try out jill v0.7.0 !
