### ISSUE TITLE
respect .bash_profile

### ISSUE THREAD

**Issue by Roger-luo** [johnnychen94/jill.py#95]
currently when jill install PATH to .bashrc, but on some machines bash will use `.bash_profile`, would be nice to let jill detect that

**Comment by johnnychen94** [comment]
Is it because `.bashrc` isn't respected by those machines or just want to maintain the `PATH` only in `.bash_profile` (and not `.bashrc`)?

If it is the latter, then you can manually ensure that symlink dir `~/.local/bin` exists in PATH and jill then won't make any PATH modifications.

https://github.com/johnnychen94/jill.py/blob/3b2a29e263ed712f54b0ad2a103083aa2f8045bb/jill/install.py#L78-L79
